import { GlobalThemeOverrides } from "naive-ui";

// 关于主题的配置文件
const lightThemeOverrides: GlobalThemeOverrides = {
  common: {},
  Button: {
    color: "#ff86a8",
    colorHover: "#ff86a8",
    colorPressed: "#ff86a8",
    colorFocus: "#ff86a8",
    // colorDisabled: '#ff86a8',
    rippleColor: "#ff86a8",
    textColor: "#ff86a8",
    textColorTertiary: "#ff86a8",
    textColorHover: "white",
    textColorPressed: "white",
    textColorFocus: "white",
    textColorDisabled: "#ff86a8",
    textColorText: "#ff86a8",
    textColorTextHover: "#6b7280",
    textColorTextPressed: "#ff86a8",
    textColorTextFocus: "#ff86a8",
    textColorTextDisabled: "#ff86a8",
    textColorGhost: "#ff86a8",
    textColorGhostHover: "#ff86a8",
    textColorGhostPressed: "#ff86a8",
    textColorGhostFocus: "#ff86a8",
    textColorGhostDisabled: "#ff86a8",
    colorPrimary: "#ff86a8",
    colorHoverPrimary: "white",
    colorPressedPrimary: "#ff86a8",
    colorFocusPrimary: "#ff86a8",
    colorDisabledPrimary: "#ff86a8",
    textColorPrimary: "#ff86a8",
    textColorHoverPrimary: "#ff86a8",
    textColorPressedPrimary: "#ff86a8",
    textColorFocusPrimary: "#ff86a8",
    textColorDisabledPrimary: "#ff86a8",
    textColorTextPrimary: "#ff86a8",
    textColorTextHoverPrimary: "#ff86a8",
    textColorTextPressedPrimary: "#ff86a8",
    textColorTextFocusPrimary: "#ff86a8",
    textColorTextDisabledPrimary: "#ff86a8",
    textColorGhostPrimary: "#ff86a8",
    textColorGhostHoverPrimary: "#ff86a8",
    textColorGhostPressedPrimary: "#ff86a8",
    textColorGhostFocusPrimary: "#ff86a8",
    textColorGhostDisabledPrimary: "#ff86a8",
    border: "1px solid #ff86a8",
    borderHover: "1px solid #ff86a8",
    borderPressed: "1px solid #ff86a8",
    borderFocus: "1px solid #ff86a8",
    borderDisabled: "1px solid #ff86a8",
    borderPrimary: "1px solid #ff86a8",
    borderHoverPrimary: "1px solid #ff86a8",
    borderPressedPrimary: "1px solid #ff86a8",
    borderFocusPrimary: "1px solid #ff86a8",
    borderDisabledPrimary: "1px solid #ff86a8",
  },
  Pagination: {
    // textColorHover: "#000",
    itemTextColorActive: "#858585",
    itemBorderActive: "1px solid #858585",
  },
  Tabs: {
    tabTextColorLine: "#a8a8a8",
    tabTextColorActiveLine: "#a8a8a8",
    tabTextColorHoverLine: "#a8a8a8",
    tabTextColorDisabledLine: "#a8a8a8",
    tabTextColorSegment: "#a8a8a8",
    tabTextColorActiveSegment: "#a8a8a8",
    tabTextColorHoverSegment: "#a8a8a8",
    tabTextColorDisabledSegment: "#a8a8a8",
    tabTextColorBar: "#a8a8a8",
    tabTextColorActiveBar: "#a8a8a8",
    tabTextColorHoverBar: "#a8a8a8",
    tabTextColorDisabledBar: "#a8a8a8",
    tabTextColorCard: "#a8a8a8",
    tabTextColorHoverCard: "#a8a8a8",
    tabTextColorActiveCard: "#a8a8a8",
    tabTextColorDisabledCard: "#a8a8a8",
    barColor: "#a8a8a8",
  },
  Table: {
    peers: {
      thColor: "white",
      borderColor: "transparent",
    },
    // --n-th-color:
  },
  Select: {
    // menuBoxShadow: "none",
    peers: {
      InternalSelectMenu: {
        // color: "transparent",
        optionFontSizeMedium: "16px",
        optionCheckColor: "#767676",
        borderRadius: "8px",
        // optionColorActive: '#767676',
        optionTextColor: "#767676",
        optionTextColorActive: "#767676",
        // optionColorActive: "#e0eaff",
        optionColorActivePending: "#e0eaff",
        optionColorPending: "#e0eaff",
        // optionColorActivePending: '#767676',
      },
      InternalSelection: {
        border: "1px solid #bfbfbf",
        borderActive: "1px solid #0256ff",
        borderFocus: "1px solid #0256ff",
        borderHover: "unset",
        borderRadius: "8px",
        boxShadowFocus: "1px solid #0256ff",
        boxShadowActive: "1px solid #0256ff",
        caretColor: "unset",
      },
    },
  },
  Input: {
    // --n-placeholder-color-disabled
    // placeholderColor: "transparent",
    // placeholderColorDisabled: "transparent",
    border: "1px solid #bfbfbf",
    borderHover: "unset",
    borderDisabled: "1px solid #0256ff",
    borderFocus: "1px solid #0256ff",
    borderRadius: "8px",
    caretColor: "unset",
    loadingColor: "unset",
    colorFocus: "unset",
    boxShadowFocus: "unset",
    // outline: "none",
    color: "transparent",
    colorDisabled: "transparent",
  },
  Checkbox: {
    color: "white",
    colorChecked: "#ff86a8",
    colorDisabled: "#ff86a8",
    colorDisabledChecked: "#ff86a8",
    colorTableHeader: "#ff86a8",
    colorTableHeaderModal: "#ff86a8",
    colorTableHeaderPopover: "#ff86a8",
    checkMarkColor: "white",
    checkMarkColorDisabled: "#ff86a8",
    checkMarkColorDisabledChecked: "#ff86a8",
    border: "1px solid  #ff86a8",
    borderDisabled: "1px solid  #ff86a8",
    borderDisabledChecked: "1px solid  #ff86a8",
    borderChecked: "1px solid  #ff86a8",
    borderFocus: "1px solid  #ff86a8",
    boxShadowFocus: "1px solid  #ff86a8",
  },
  Menu: {
    // --n-item-text-color-active
    // color: '#ff86a8',
    // groupTextColor: '#ff86a8',
    itemColorHover: "#f3f3f5",
    itemColorActive: "unset",
    itemColorActiveHover: "#f3f3f5",
    // itemColorActiveCollapsed: '#ffcfe8',
    // itemTextColor: '#ff86a8',
    itemTextColorHover: "black",
    itemTextColorActive: "black",
    itemTextColorActiveHover: "black",
    // itemTextColorChildActive: '#ff86a8',
    // itemTextColorChildActiveHover: '#ff86a8',
    // itemTextColorHorizontal: '#ff86a8',
    // itemTextColorHoverHorizontal: '#ff86a8',
    // itemTextColorActiveHorizontal: '#ff86a8',
    // itemTextColorActiveHoverHorizontal: '#ff86a8',
    // itemTextColorChildActiveHorizontal: '#ff86a8',
    // itemTextColorChildActiveHoverHorizontal: '#ff86a8',
    // itemIconColor: '#ff86a8',
    // itemIconColorHover: '#ff86a8',
    // itemIconColorActive: '#ff86a8',
    // itemIconColorActiveHover: '#ff86a8',
    // itemIconColorChildActive: '#ff86a8',
    // itemIconColorChildActiveHover: '#ff86a8',
    // itemIconColorCollapsed: '#ff86a8',
    // itemIconColorHorizontal: '#ff86a8',
    // itemIconColorHoverHorizontal: '#ff86a8',
    // itemIconColorActiveHorizontal: '#ff86a8',
    // itemIconColorActiveHoverHorizontal: '#ff86a8',
    // itemIconColorChildActiveHorizontal: '#ff86a8',
    // itemIconColorChildActiveHoverHorizontal: '#ff86a8',
    // arrowColor: '#ff86a8',
    arrowColorHover: "#ff86a8",
    arrowColorActive: "#ff86a8",
    arrowColorActiveHover: "#ff86a8",
    arrowColorChildActive: "#ff86a8",
    arrowColorChildActiveHover: "#ff86a8",
    peers: {
      Dropdown: {
        // color: '#ff86a8',
        optionTextColor: "black",
        optionTextColorHover: "#ff86a8",
        optionTextColorActive: "#ff86a8",
        optionTextColorChildActive: "#ff86a8",
        optionColorHover: "#ffcfe8",
        optionColorActive: "#ffcfe8",
      },
    },
  },
  Dialog: {
    iconColorInfo: "#ff86a8",
    titleFontWeight: "600",
    borderRadius: "16px",
  },
  BackTop: {
    iconColorHover: "#ff0087FF",
    iconColorPressed: "#f757acFF",
  },
  // Switch: {
  //   railColorActive: '#ff86a8',
  //   loadingColor: '#ff86a8',
  //   boxShadowFocus: '0 0 0 2px #ff1f96;',
  // },
  Tag: {
    borderRadius: "8px",
  },
};

const darkThemeOverrides = {
  common: {
    // primaryColor: 'white',
    // primaryColorHover: 'white',
    // primaryColorPressed: 'black',
    // buttonColor2: '#ff86a8',
    // buttonColor2Hover: '#ff86a8',
    // buttonColor2Pressed: '#ff86a8',
  },
  Button: {
    color: "#ff86a8",
    colorHover: "#ff86a8",
    colorPressed: "#ff86a8",
    colorFocus: "#ff86a8",
    // colorDisabled: '#ff86a8',
    rippleColor: "#ff86a8",
    textColor: "#ff86a8",
    textColorTertiary: "#ff86a8",
    textColorHover: "white",
    textColorPressed: "white",
    textColorFocus: "white",
    textColorDisabled: "#ff86a8",
    textColorText: "#ff86a8",
    textColorTextHover: "#6b7280",
    textColorTextPressed: "#ff86a8",
    textColorTextFocus: "#ff86a8",
    textColorTextDisabled: "#ff86a8",
    textColorGhost: "#ff86a8",
    textColorGhostHover: "#ff86a8",
    textColorGhostPressed: "#ff86a8",
    textColorGhostFocus: "#ff86a8",
    textColorGhostDisabled: "#ff86a8",
    colorPrimary: "#ff86a8",
    colorHoverPrimary: "white",
    colorPressedPrimary: "#ff86a8",
    colorFocusPrimary: "#ff86a8",
    colorDisabledPrimary: "#ff86a8",
    textColorPrimary: "#ff86a8",
    textColorHoverPrimary: "#ff86a8",
    textColorPressedPrimary: "#ff86a8",
    textColorFocusPrimary: "#ff86a8",
    textColorDisabledPrimary: "#ff86a8",
    textColorTextPrimary: "#ff86a8",
    textColorTextHoverPrimary: "#ff86a8",
    textColorTextPressedPrimary: "#ff86a8",
    textColorTextFocusPrimary: "#ff86a8",
    textColorTextDisabledPrimary: "#ff86a8",
    textColorGhostPrimary: "#ff86a8",
    textColorGhostHoverPrimary: "#ff86a8",
    textColorGhostPressedPrimary: "#ff86a8",
    textColorGhostFocusPrimary: "#ff86a8",
    textColorGhostDisabledPrimary: "#ff86a8",
    border: "1px solid #ff86a8",
    borderHover: "1px solid #ff86a8",
    borderPressed: "1px solid #ff86a8",
    borderFocus: "1px solid #ff86a8",
    borderDisabled: "1px solid #ff86a8",
    borderPrimary: "1px solid #ff86a8",
    borderHoverPrimary: "1px solid #ff86a8",
    borderPressedPrimary: "1px solid #ff86a8",
    borderFocusPrimary: "1px solid #ff86a8",
    borderDisabledPrimary: "1px solid #ff86a8",
  },
  Pagination: {
    textColorHover: "#000",
  },
  Tabs: {
    tabTextColorLine: "#a8a8a8",
    tabTextColorActiveLine: "#a8a8a8",
    tabTextColorHoverLine: "#a8a8a8",
    tabTextColorDisabledLine: "#a8a8a8",
    tabTextColorSegment: "#a8a8a8",
    tabTextColorActiveSegment: "#a8a8a8",
    tabTextColorHoverSegment: "#a8a8a8",
    tabTextColorDisabledSegment: "#a8a8a8",
    tabTextColorBar: "#a8a8a8",
    tabTextColorActiveBar: "#a8a8a8",
    tabTextColorHoverBar: "#a8a8a8",
    tabTextColorDisabledBar: "#a8a8a8",
    tabTextColorCard: "#a8a8a8",
    tabTextColorHoverCard: "#a8a8a8",
    tabTextColorActiveCard: "#a8a8a8",
    tabTextColorDisabledCard: "#a8a8a8",
    barColor: "#a8a8a8",
  },
  Select: {
    peers: {
      InternalSelectMenu: {
        optionCheckColor: "#ff86a8",
        // optionColorActive: '#ff86a8',
        optionTextColorActive: "#ff86a8",
        // optionColorPending: '#ff86a8',
        // optionColorActivePending: '#ff86a8',
      },
      InternalSelection: {
        border: "unset",
        borderActive: "unset",
        borderFocus: "unset",
        borderHover: "unset",
        boxShadowFocus: "unset",
        boxShadowActive: "unset",
        caretColor: "unset",
      },
    },
  },
  Input: {
    border: "1px solid pink",
    borderHover: "1px solid pink",
    borderDisabled: "1px solid pink",
    borderFocus: "1px solid pink",
    caretColor: "unset",
    loadingColor: "unset",
    colorFocus: "unset",
    boxShadowFocus: "unset",
    outline: "none",
    color: "transparent",
  },
  Checkbox: {
    color: "white",
    colorChecked: "#ff86a8",
    colorDisabled: "#ff86a8",
    colorDisabledChecked: "#ff86a8",
    colorTableHeader: "#ff86a8",
    colorTableHeaderModal: "#ff86a8",
    colorTableHeaderPopover: "#ff86a8",
    checkMarkColor: "white",
    checkMarkColorDisabled: "#ff86a8",
    checkMarkColorDisabledChecked: "#ff86a8",
    border: "1px solid  #ff86a8",
    borderDisabled: "1px solid  #ff86a8",
    borderDisabledChecked: "1px solid  #ff86a8",
    borderChecked: "1px solid  #ff86a8",
    borderFocus: "1px solid  #ff86a8",
    boxShadowFocus: "1px solid  #ff86a8",
  },
  Menu: {
    // --n-item-text-color-active
    // color: '#ff86a8',
    // groupTextColor: '#ff86a8',
    // itemColorHover: '#ff54af',
    itemColorActive: "#ffcfe8",
    itemColorActiveHover: "#ffcfe8",
    itemColorActiveCollapsed: "#ffcfe8",
    // itemTextColor: '#ff86a8',
    itemTextColorHover: "#ff86a8",
    itemTextColorActive: "#ff86a8",
    itemTextColorActiveHover: "#ff86a8",
    itemTextColorChildActive: "#ff86a8",
    itemTextColorChildActiveHover: "#ff86a8",
    itemTextColorHorizontal: "#ff86a8",
    itemTextColorHoverHorizontal: "#ff86a8",
    itemTextColorActiveHorizontal: "#ff86a8",
    itemTextColorActiveHoverHorizontal: "#ff86a8",
    itemTextColorChildActiveHorizontal: "#ff86a8",
    itemTextColorChildActiveHoverHorizontal: "#ff86a8",
    itemIconColor: "#ff86a8",
    itemIconColorHover: "#ff86a8",
    itemIconColorActive: "#ff86a8",
    itemIconColorActiveHover: "#ff86a8",
    itemIconColorChildActive: "#ff86a8",
    itemIconColorChildActiveHover: "#ff86a8",
    itemIconColorCollapsed: "#ff86a8",
    itemIconColorHorizontal: "#ff86a8",
    itemIconColorHoverHorizontal: "#ff86a8",
    itemIconColorActiveHorizontal: "#ff86a8",
    itemIconColorActiveHoverHorizontal: "#ff86a8",
    itemIconColorChildActiveHorizontal: "#ff86a8",
    itemIconColorChildActiveHoverHorizontal: "#ff86a8",
    // arrowColor: '#ff86a8',
    arrowColorHover: "#ff86a8",
    arrowColorActive: "#ff86a8",
    arrowColorActiveHover: "#ff86a8",
    arrowColorChildActive: "#ff86a8",
    arrowColorChildActiveHover: "#ff86a8",
    peers: {
      Dropdown: {
        // color: '#ff86a8',
        optionTextColor: "black",
        optionTextColorHover: "#ff86a8",
        optionTextColorActive: "#ff86a8",
        optionTextColorChildActive: "#ff86a8",
        optionColorHover: "#ffcfe8",
        optionColorActive: "#ffcfe8",
      },
    },
  },
  Dialog: {
    iconColorInfo: "#ff86a8",
    titleFontWeight: "600",
    borderRadius: "16px",
  },
  BackTop: {
    iconColorHover: "#ff0087FF",
    iconColorPressed: "#f757acFF",
  },
  // Switch: {
  //   railColorActive: '#ff86a8',
  //   loadingColor: '#ff86a8',
  //   boxShadowFocus: '0 0 0 2px #ff1f96;',
  // },
};
export { lightThemeOverrides, darkThemeOverrides };
